### PR TITLE
Meringue config syntax fix

### PR DESCRIPTION
**Pull request by shdam**
Not sure if this will solve the other issue. But Meringue seems to run on the test set.

### CODE REVIEW

**Comment by peicai** [comment]
> Not sure if this will solve the other issue. But Meringue seems to run on the test set.

Yep, I fixed this on the cluster, but thanks! I guess you used the calculated dimensionality reduction matrix instead of Meringue's preprocessing step if you used the current version of the `meringue_optargs.json` file.

**Comment by shdam** [comment]
I ran using a test script, which ignores the optargs.

Reading the error message again, it seems the answer is in this line:
`QH6239 Qhull precision error: Initial simplex is cocircular or cospherical.  Use option 'Qz' for the Delaunay triangulation or Voronoi diagram of cocircular/cospherical points.  Option 'Qz' adds a point "at infinity".  Use option 'Qs' to search all points for the initial simplex.
`

Which dataset causes the error? - Perhaps the spots have a non-default geometry

**Comment by peicai** [comment]
The LIBD data... One option is that I could modify the `getSpatialNeighbors` function by testing different options, like 'Qz' or 'Qs'. Alternatively, I could apply Meringue to another dataset to see whether the issue is due to the spot resolution. However, in the SpaceFlow paper, they successfully applied Meringue to the LIBD data.

**Comment by shdam** [comment]
Hmm, the test script also uses LIBD. Are you running the script as it is on the native branch?

**Comment by peicai** [comment]
Yes, I ran the script as it is on the native branch, only fixing the syntax in the config and updating the optargs. It might be related to the SLURM cluster setup, as I tested it on JupyterHub and it works.

**Comment by Jieran-S** [comment]
Hi, forgot to mention here but I fixed the meringue bug by removing the identical z-axis of the dataset (which costs the breaking down of the Delaunay function) in #319. I will close this PR along with issue #316

**Pull request closed without merging**
