### PR TITLE
Spice mix gpu

### PR DESCRIPTION
**Pull request by Jieran-S**
Attempts to fix issue #225: make cpu available for the current pipeline.

Check issue for detailed description

### CODE REVIEW

**Comment by niklasmueboe** [comment]
If we check if gpu is available I think we can also remove the "device" from the config.

Is specifying the device number necessary, i.e.e does it need to be "cuda:0"?

**Comment by Jieran-S** [comment]
Agree. Will remove the device from config.

I have the same question regarding the device number. I think @alam-shahul made those specifications in the first place.

**Review by alam-shahul — COMMENTED** [review]
I guess another way to do this would be to just leave the `"device"` field out from the config file if there is no GPU; this would use the `"cpu"` device by default, as per line 163: https://github.com/SpatialHackathon/SpaceHack2023/pull/231/files#diff-5615d1512910769a2c993538dc9bf8b5f2dfa026b30bb3ea874b5d9950cf6a9aL163

**Comment by Jieran-S** [comment]
Thank you for the comment! Since SpiceMix should be used in GPU, it would be nice to explicitly set the device (cuda) in config and only use CPU as a secondary option when cuda is not available. So I changed the code accordingly.

**Review by shdam — APPROVED** [review]

**Pull request merged**
