### PR TITLE
Centralized resolution search for Banksy

### PR DESCRIPTION
**Pull request by shdam**
I added an `extract_nclust` input that should be the function to get the number of clusters in the output. Do you have any comments on this implementation?

### CODE REVIEW

**Comment by shdam** [comment]
It seems there are issues sourcing the search_res script. @Jieran-S How would it work in snakemake? Can I hardcode the path or is there a better way?

**Comment by Jieran-S** [comment]
Hey, what do you mean by hard-coding? If it's hard-coding an absolute path, it would not be a good idea as the GitHub directory can change when adapted to another system. 

We do can take advantage of the defined relative position between the function script and the method script: For python, what I did was to take the parent folder of the method script into the system path, and import the `binary_seach` module from `search_res.py`. 

Is there any way in R to identify the script path and find the path for its parent folder, then source the script by `source(sprintf("%s/search_res.r", parent_folder))` or something like that? :))

**Comment by shdam** [comment]
I would have to install a separate package (sourcetools) to get the path of the source file.
But if I know what the working directory is when running snakemake, I can just make a relative path.

**Comment by shdam** [comment]
@Jieran-S and @peicai Please review this when you have time, future implementations rely on it :)

**Comment by Jieran-S** [comment]
Sorry for the late reply!! was too caught up in writing. Looks good. :))

**Review by Jieran-S — APPROVED** [review]

**Comment by Jieran-S** [comment]
Thanks for implementing. This should work as long as the relative location is the same. Good that we don't have to add a new package to all those methods. I will test its integration with the pipeline next week or the week after. Thanks!

**Comment by shdam** [comment]
Fair enough - happy writing! :)

**Pull request merged**
