### PR TITLE
Native bass - minor changes to implementation

### PR DESCRIPTION
**Pull request by shdam**
The code wasn't compatible with Visium/ST. I fixed a typo in the configs and added to params that sometimes differ from default. Removed extra configs and some non-used code.

### CODE REVIEW

**Comment by peicai** [comment]
Everything looks good. For configurations, should we only keep the default configuration and the ones used in the examples, without extra configurations that tune parameters like beta_method and geneSelect?

**Comment by shdam** [comment]
That was my assumption to not bloat it. Also, if they don't showcase other settings, who would use them?
Perhaps if we end up with less than 3 configurations, we can consider it?

**Comment by Jieran-S** [comment]
For the config, I agree with @shdam but decided to keep the extra config when reviewing the PR on GraphST, STAGATE, and bass. My rationale is that we can keep those configurations but not use them in Snakemake when running the workflow, just in case we change our mind and want to use them in the future. 

In snakemake `path_config` folder, we can specify which configuration to use. For the next round of result snapshot, I will make sure we only use those configurations that are specified by the author (those config_{name})

**Comment by shdam** [comment]
That's fair. I added in the configs again :)

**Review by Jieran-S — APPROVED** [review]

**Pull request merged**
