### PR TITLE
Visium hd cancer colon

### LINKED ISSUE #305: Visium HD colon cancer
Annotated by a pathologist for Spacehack

Contains 3 bin levels 2,8 and 16 µm bins
Additionaly contains nuclei segmentation, in which squares were assigned to the closest nuclei

### PR DESCRIPTION
**Pull request by pakiessling**
Closes #305

### CODE REVIEW

**Review by Jieran-S — APPROVED** [review]
Looking good. Can you also specify how the annotation is done in the meta-sheet? Are there any other labels besides "annot_type" that can be potentially used?

**Comment by pakiessling** [comment]
Hi Jieran, do you mean observation level metadata?
10x didnt supply cell types or similiar for this dataset.
As the bins are not really "single cell" level I am not sure how to best annotate those.
How was this done for other Visium flavors?

**Comment by Jieran-S** [comment]
Oh I simply mean the [google sheet](https://docs.google.com/spreadsheets/d/1QCeAF4yQG4bhZSGPQwwVBj_XF7ADY_2mK5xivAIfHsc/edit?usp=sharing) we use to track the metadata on the "Annotate how?" column. 

I found the information from that column very helpful when writing up my thesis. I think we might need to use it in the future for writing.

**Comment by pakiessling** [comment]
Ah gotcha, yeah I will fill it in.
Btw how is the thesis going? Did you defend yet?

**Comment by Jieran-S** [comment]
Yesss...Will be this thursday haha! It'll be on [zoom](https://uzh.zoom.us/j/95066835829?pwd=c1paN2puMDFBUWI2OC9ibk8walZ2Zz09) 12:15-13:00. Come join if you have time! (Finger crossed XD)

**Pull request merged**
