### PR TITLE
Data her2st breast cancer tiesmeyer

### PR DESCRIPTION
**Pull request by sebastiantiesmeyer**
issue: https://github.com/SpatialHackathon/SpaceHack2023/issues/37

### CODE REVIEW

**Comment by pakiessling** [comment]
Hi @sebastiantiesmeyer how are we doing here? What needs to be done?

**Comment by sebastiantiesmeyer** [comment]
Hi and thanks for following up on this!
This commit is still waiting for an approval by @svedziok; it should be ready to merge afterwards : )

**Comment by pakiessling** [comment]
@kbiharie @peicai 

Maybe one of you can take a look so we finish this one?

**Comment by Jieran-S** [comment]
Seems good to go! @pakiessling think we can merge this one? ST might not be our focus but good to have some non-brain dataset in the repo?

**Review by pakiessling — COMMENTED** [review]
Looks good to me.
Eventually we should probably move over to a more solid downloading function but we can do that for all scripts at once

**Review by Jieran-S — APPROVED** [review]

**Pull request merged**
