### PR TITLE
Native Seurat

### PR DESCRIPTION
**Pull request by Jieran-S**
So for Seurat, I tested both Louvain and Leiden clustering implemented in Seurat. Both of which I generated 4 configurations.

The configurations were based on their vignettes. Check the reference links in each config for details.

### CODE REVIEW

**Comment by shdam** [comment]
I'd say having both leiden and louvain is overkill, as they are very similar.
Both n_genes and n_pcs should be input params, and a highly variable genes step could also be useful. Binary_search should preferably also be imported from script. I can add those later if you are pressed on time.

**Comment by Jieran-S** [comment]
I agree....I configured it this way as I want to compare a bit both louvain and leiden. Maybe we can delete the louvain configs as Leiden supersedes them.

> Both n_genes and n_pcs should be input params, and a highly variable genes step could also be useful.

Agree! Should n_pcs and n_genes be input params in general? I can adjust other method configs that only distinguish by n_pcs. Thanks for reminding we omit the hvg part.

>  Binary_search should preferably also be imported from script.

Agree...Probably didn't keep everything up to date due to that project time limit. Same for Stardust I will point it out.

>  I can add those later if you are pressed on time.

That will be great. If I have time to do it I will also lyk. :)) Thanks a lot!!

**Comment by Jieran-S** [comment]
Hi, I've updated Seurat:
1. delete all louvain configuration
2. Adding n_pcs and n_genes into input params
3. Added an HVG selection procedure. 

But is an HVG selection procedure necessary? Check the two vignette that uses scTransform, they didn't have any HVG selection processes ([Vignette1](https://satijalab.org/seurat/articles/seurat5_spatial_vignette_2), [Vignette2](https://satijalab.org/seurat/articles/spatial_vignette)). The only one using HVG selection ([Vignette3](https://satijalab.org/seurat/articles/visiumhd_analysis_vignette#unsupervised-clustering)) doesn't use scTransform.

**Comment by shdam** [comment]
SCTransform uses 3000 variable features by default: [https://satijalab.org/seurat/reference/sctransform](https://satijalab.org/seurat/reference/sctransform)
Perhaps that is where n_genes should be used? I.e., `variable.features.n = n_genes`

**Review by shdam — APPROVED** [review]

**Pull request merged**
